version: "3.8"

services:

  client:
    build: ./client
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev"]
    volumes:
      - ./client:/src
      - /src/node_modules
    depends_on:
      - server

  server:
    build: ./server
    container_name: workforce-server-1
    ports:
      - "8800:8800"
    working_dir: /src
    command: ["npm", "run", "start"]
    volumes:
      - ./server:/src
      - /node_modules
    env_file:
      - ./server/.env       # âœ… explicit path
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    container_name: workforce-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      DB_HOST: mysql
      command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
