services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev"]
    volumes:
      - ./client:/app              
      - /app/node_modules    
    depends_on:
      - server

  server:
    build: ./server
    container_name: workforce-server-1
    ports:
      - "8800:8800"
    working_dir: /src
    command: ["npm", "run", "dev"] 
    volumes:
      - ./server:/src                
      - /src/node_modules           
    env_file:
      - ./server/.env
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    container_name: workforce-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      DB_HOST: workforce-mysql-1
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - workforce_mysql-data:/var/lib/mysql

volumes:
  workforce_mysql-data:
    external: true